export const items = [
  { id: 1, name: "A", text: "Letter A" },
  { id: 2, name: "B", text: "Letter B" },
  { id: 3, name: "C", text: "Letter C" },
  { id: 4, name: "D", text: "Letter D" },
  { id: 5, name: "E", text: "Letter E" },
  { id: 6, name: "F", text: "Letter F" },
  { id: 7, name: "G", text: "Letter G" },
  { id: 8, name: "H", text: "Letter H" },
  { id: 9, name: "I", text: "Letter I" },
  { id: 10, name: "J", text: "Letter J" },
  { id: 11, name: "K", text: "Letter K" },

  { id: 12, name: "L", text: "Letter L" },
  { id: 13, name: "M", text: "Letter M" },
  { id: 14, name: "N", text: "Letter N" },
  { id: 15, name: "O", text: "Letter O" },
  { id: 16, name: "P", text: "Letter P" },
  { id: 17, name: "Q", text: "Letter Q" },
  { id: 18, name: "R", text: "Letter R" },
  { id: 19, name: "S", text: "Letter S" },
  { id: 20, name: "T", text: "Letter T" },
  { id: 21, name: "U", text: "Letter U" },
  { id: 22, name: "V", text: "Letter V" },

  { id: 23, name: "W", text: "Letter W" },
  { id: 24, name: "X", text: "Letter X" },

  { id: 25, name: "Y", text: "Letter Y" },
  { id: 26, name: "Z", text: "Letter Z" },
];
